# Generated by Django 3.2.5 on 2021-07-21 06:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField(max_length=650)),
            ],
            options={
                'verbose_name_plural': 'Chronologies',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('massage', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_photo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('short_description', models.TextField(max_length=650)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('file', models.FileField(upload_to='files/')),
                ('region', models.CharField(choices=[('Chuy', 'Чуй'), ('Bishkek', 'Бишкек'), ('Issyk-Kul', 'Иссык-Куль'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Osh', 'Ош'), ('Batken', 'Баткен'), ('Jalal-Abad', 'Жалал-Абад')], max_length=200)),
                ('contribution', models.DecimalField(decimal_places=0, max_digits=19)),
                ('project_url', models.CharField(blank=True, max_length=100)),
                ('project_number', models.IntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'Альянсы для устойчивого развития'), ('2', 'Государственное управление, мир и безопасность'), ('3', 'Партнерство в сфере миграции'), ('4', 'Цифровизация наука, технологии и инновации'), ('5', 'Зеленая экономика')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project Galleries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.news')),
            ],
            options={
                'verbose_name_plural': 'News Galleries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='you can upload image or video', upload_to='images/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery Files',
                'ordering': ['-id'],
            },
        ),
    ]
